import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Check, Heart, LoaderCircle, Music2, Sparkles, WandSparkles } from "lucide-react";
import "@/App.css";
import "@/AppOverrides.css";

const CLIENT_ID = process.env.REACT_APP_SPOTIFY_CLIENT_ID;
const REDIRECT_URI = process.env.REACT_APP_SPOTIFY_REDIRECT_URI || `${window.location.origin}/`;
const SCOPES = "playlist-modify-private";
const moods = [
  { id: "soft", label: "Soft & floaty", note: "for the days that feel like satin", query: "Daniel Caesar The 1975 soft R&B" },
  { id: "main-character", label: "Main character", note: "a little drama, a lot of sparkle", query: "Drake Travis Scott A$AP Rocky main character" },
  { id: "healing", label: "Healing era", note: "slow songs for a tender heart", query: "Daniel Caesar SZA healing R&B" },
  { id: "late-night", label: "After midnight", note: "city lights and honest feelings", query: "The 1975 Kanye West late night" },
  { id: "unbothered", label: "Unbothered", note: "pretty, powerful, completely yours", query: "A$AP Rocky Rihanna confident" },
];
const tracks = [
  ["Best Part", "Daniel Caesar · H.E.R.", "Freudian", "Best Part Daniel Caesar H.E.R."], ["Love It If We Made It", "The 1975", "A Brief Inquiry into Online Relationships", "Love It If We Made It The 1975"], ["SKELETONS", "Travis Scott", "ASTROWORLD", "SKELETONS Travis Scott"], ["Passionfruit", "Drake", "More Life", "Passionfruit Drake"], ["L$D", "A$AP Rocky", "AT.LONG.LAST.A$AP", "L$D A$AP Rocky"], ["Nights", "Frank Ocean", "Blonde", "Nights Frank Ocean"], ["Pink + White", "Frank Ocean", "Blonde", "Pink White Frank Ocean"], ["Waves", "Kanye West", "The Life of Pablo", "Waves Kanye West"], ["The Weekend", "SZA", "Ctrl", "The Weekend SZA"], ["Japanese Denim", "Daniel Caesar", "Freudian", "Japanese Denim Daniel Caesar"], ["Love Me Harder", "Ariana Grande · The Weeknd", "My Everything", "Love Me Harder Ariana Grande The Weeknd"], ["Love Story", "Taylor Swift", "Fearless", "Love Story Taylor Swift"], ["Nothin' On You", "B.o.B · Bruno Mars", "B.o.B Presents", "Nothin On You B.o.B Bruno Mars"], ["Sweet Disposition", "The Temper Trap", "Conditions", "Sweet Disposition The Temper Trap"], ["Robbers", "The 1975", "The 1975", "Robbers The 1975"], ["Self Control", "Frank Ocean", "Blonde", "Self Control Frank Ocean"], ["Crew", "GoldLink · Brent Faiyaz", "At What Cost", "Crew GoldLink Brent Faiyaz"], ["Love Galore", "SZA · Travis Scott", "Ctrl", "Love Galore SZA Travis Scott"], ["After Dark", "Mr.Kitty", "Time", "After Dark Mr Kitty"], ["I Wanna Be Yours", "Arctic Monkeys", "AM", "I Wanna Be Yours Arctic Monkeys"],
].map(([name, artist, album, query]) => ({ name, artist, album, query }));

const spotifySearch = (query) => `https://open.spotify.com/search/${encodeURIComponent(query)}`;
const base64Url = (buffer) => btoa(String.fromCharCode(...new Uint8Array(buffer))).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
async function createVerifier() { const bytes = new Uint8Array(64); crypto.getRandomValues(bytes); return base64Url(bytes); }
async function createChallenge(verifier) { return base64Url(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(verifier))); }

export default function App() {
  const [mood, setMood] = useState("soft");
  const [feeling, setFeeling] = useState("");
  const [generated, setGenerated] = useState(false);
  const [token, setToken] = useState(localStorage.getItem("harswaggitify_access_token"));
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const selectedMood = useMemo(() => moods.find((item) => item.id === mood), [mood]);

  useEffect(() => {
    const code = new URLSearchParams(window.location.search).get("code");
    if (!code) return;
    const verifier = localStorage.getItem("harswaggitify_code_verifier");
    if (!verifier) return;
    fetch("https://accounts.spotify.com/api/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: CLIENT_ID, grant_type: "authorization_code", code, redirect_uri: REDIRECT_URI, code_verifier: verifier }) }).then((response) => response.json()).then((data) => { if (!data.access_token) throw new Error("Spotify authorization failed"); localStorage.setItem("harswaggitify_access_token", data.access_token); setToken(data.access_token); window.history.replaceState({}, "", "/"); const pending = localStorage.getItem("harswaggitify_pending_playlist"); if (pending) createPlaylist(data.access_token, JSON.parse(pending)); }).catch(() => setMessage("Spotify authorization did not finish. Please try again."));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const connectSpotify = async (pending) => { const verifier = await createVerifier(); const challenge = await createChallenge(verifier); localStorage.setItem("harswaggitify_code_verifier", verifier); localStorage.setItem("harswaggitify_pending_playlist", JSON.stringify(pending)); const params = new URLSearchParams({ client_id: CLIENT_ID, response_type: "code", redirect_uri: REDIRECT_URI, code_challenge_method: "S256", code_challenge: challenge, scope: SCOPES }); window.location.href = `https://accounts.spotify.com/authorize?${params}`; };
  const surprise = () => { setMood(moods[Math.floor(Math.random() * moods.length)].id); setFeeling("surprise me with something beautiful"); setGenerated(false); };
  const makePlaylist = () => setGenerated(true);
  const createPlaylist = async (activeToken = token, pending = { mood: selectedMood, feeling, tracks }) => { setBusy(true); setMessage("Finding the best versions of your 20 songs..."); try { if (!activeToken) return connectSpotify(pending); const headers = { Authorization: `Bearer ${activeToken}`, "Content-Type": "application/json" }; const uris = []; for (const track of tracks) { const result = await fetch(`https://api.spotify.com/v1/search?${new URLSearchParams({ q: track.query, type: "track", limit: "1" })}`, { headers }); const data = await result.json(); if (data.tracks?.items?.[0]?.uri) uris.push(data.tracks.items[0].uri); } if (!uris.length) throw new Error("No tracks found"); const profile = await fetch("https://api.spotify.com/v1/me", { headers }).then((response) => response.json()); const playlist = await fetch(`https://api.spotify.com/v1/users/${profile.id}/playlists`, { method: "POST", headers, body: JSON.stringify({ name: `For Harshita · ${pending.mood.label}`, description: `Made with love, especially for Harshita. ${pending.feeling || pending.mood.note}`, public: false }) }).then((response) => response.json()); await fetch(`https://api.spotify.com/v1/playlists/${playlist.id}/items`, { method: "POST", headers, body: JSON.stringify({ uris }) }); localStorage.removeItem("harswaggitify_pending_playlist"); setMessage(`${uris.length} songs were added to “${playlist.name}”.`); } catch { setMessage("Spotify could not create the playlist. Please reconnect and try again."); } finally { setBusy(false); } };

  return <main className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark"><Heart size={16} fill="currentColor" /></span><span>Harswaggitify</span></div><span className="profile-chip" data-testid="profile-chip"><Heart size={14} fill="currentColor" /> made for Harshita</span></header><section className="app-content"><div className="greeting"><p className="eyebrow">A playlist, made in your language <Sparkles size={14} /></p><h1>How is your heart<br /><em>singing</em> today?</h1><p>Choose a feeling. Add a little context. I’ll find the songs that get it.</p></div><div className="mood-grid">{moods.map((item) => <button data-testid={`mood-${item.id}-button`} key={item.id} className={`mood-button ${mood === item.id ? "selected" : ""}`} onClick={() => { setMood(item.id); setGenerated(false); }}><span>{item.label}</span><small>{item.note}</small>{mood === item.id && <Check size={17} />}</button>)}</div><div className="feeling-row"><label htmlFor="feeling">Add a little more, if you want to</label><textarea data-testid="feeling-input" id="feeling" value={feeling} onChange={(event) => { setFeeling(event.target.value); setGenerated(false); }} placeholder="e.g. I want to feel like the city belongs to me..." /><button data-testid="surprise-me-button" className="surprise-button" onClick={surprise}><WandSparkles size={17} /> Surprise me</button></div><div className="action-row"><div><span className="selected-label">Selected feeling</span><strong>{selectedMood.label}</strong></div><button data-testid="make-playlist-button" className="primary-button" onClick={makePlaylist}>Make my playlist <ArrowUpRight size={17} /></button></div>{generated && <PlaylistPreview query={feeling || selectedMood.query} onCreate={() => createPlaylist()} busy={busy} message={message} />}</section></main>;
}

function PlaylistPreview({ query, onCreate, busy, message }) { return <section className="playlist-preview"><div className="preview-heading"><div><p className="eyebrow">Your little soundtrack <Music2 size={14} /></p><h2>Made for Harshita</h2></div><span className="track-count">20 songs</span></div><p className="preview-note">Confirm once and Harswaggitify will create a private playlist in your Spotify account with all 20 songs.</p><div className="track-list">{tracks.map((track, index) => <a data-testid={`spotify-search-${index + 1}-link`} className="track" key={track.name} href={spotifySearch(track.query || query)} target="_blank" rel="noreferrer"><span className="track-number">{String(index + 1).padStart(2, "0")}</span><span className="cover-art"><Music2 size={18} /></span><span><strong>{track.name}</strong><small>{track.artist}</small></span><span className="album-name">{track.album}</span><ArrowUpRight size={15} className="track-arrow" /></a>)}</div><button data-testid="create-spotify-playlist-button" className="confirm-button" onClick={onCreate} disabled={busy}>{busy ? <><LoaderCircle size={17} className="spin" /> {message || "Creating your playlist..."}</> : <>Create this playlist in Spotify <ArrowUpRight size={17} /></>}</button>{message && !busy && <p data-testid="playlist-status-message" className="preview-note">{message}</p>}</section>; }